clearvars
close all

root='D:\Ruonan\Projects in the lab\VA_RA_PTB\Clinical and behavioral';
% filename = [root,'\Clinical_Behavioral_040518.txt'];
% % data=tdfread(filename);
% tb = readtable(filename);

load(fullfile(root,'all data_male.mat'));
% load(fullfile(root,'all data.mat'));


%% Calculate components PCA 11 measures
include_gain = tb.isExcluded_behavior == 0 & tb.isGain == 1;
include_loss = tb.isExcluded_behavior == 0 & tb.isGain == 0;

include = include_gain;

% load PCA loadings
loadingsfilename = fullfile(root,'pca loadings 11.xlsx');

loadings = readtable(loadingsfilename);


% calculate PCA component
tb.cp1 = nanzscore([tb.caps_totalscorem,...
    tb.pclm_total,...
    tb.ctq_total,tb.ces_total,tb.drri2_combat_exposure_total,...
    tb.bdiii_total,tb.stai_x1_total, tb.stai_x2_total,...
    tb.bai_total,...
    tb.ders_total,tb.des_total_mean])...
    * table2array(loadings(:,2));

tb.cp2 = nanzscore([tb.caps_totalscorem,...
    tb.pclm_total,...
    tb.ctq_total,tb.ces_total,tb.drri2_combat_exposure_total,...
    tb.bdiii_total,tb.stai_x1_total, tb.stai_x2_total,...
    tb.bai_total,...
    tb.ders_total,tb.des_total_mean])...
    * table2array(loadings(:,3));

tb.cp3 = nanzscore([tb.caps_totalscorem,...
    tb.pclm_total,...
    tb.ctq_total,tb.ces_total,tb.drri2_combat_exposure_total,...
    tb.bdiii_total,tb.stai_x1_total, tb.stai_x2_total,...
    tb.bai_total,...
    tb.ders_total,tb.des_total_mean])...
    * table2array(loadings(:,4));

tb.cp4 = nanzscore([tb.caps_totalscorem,...
    tb.pclm_total,...
    tb.ctq_total,tb.ces_total,tb.drri2_combat_exposure_total,...
    tb.bdiii_total,tb.stai_x1_total, tb.stai_x2_total,...
    tb.bai_total,...
    tb.ders_total,tb.des_total_mean])...
    * table2array(loadings(:,5));

tb.cp5 = nanzscore([tb.caps_totalscorem,...
    tb.pclm_total,...
    tb.ctq_total,tb.ces_total,tb.drri2_combat_exposure_total,...
    tb.bdiii_total,tb.stai_x1_total, tb.stai_x2_total,...
    tb.bai_total,...
    tb.ders_total,tb.des_total_mean])...
    * table2array(loadings(:,6));

%% create table for multilinear model PCA 11
tb2ml = table(tb.id(include), tb.age(include),...
    tb.caps_totalscorem(include),tb.caps_totalscorel(include),...
    tb.pclm_total(include),...
    tb.ctq_total(include),tb.ces_total(include),tb.drri2_combat_exposure_total(include),...
    tb.bdiii_total(include),tb.stai_x1_total(include), tb.stai_x2_total(include),...
    tb.bai_total(include),...
    tb.asi_alcohol(include),tb.asi_drug(include),...
    tb.ders_total(include),tb.des_total_mean(include),tb.fssii_total(include),...
    tb.rses_total(include),tb.rlocscale_total(include),...
    ...
    tb.R_F_I_PastMonth_(include),...
    tb.A_F_I_PastMonth_(include), tb.N_F_I_PastMonth_(include),...
    tb.DA_F_I_PastMonth_(include), tb.AA_F_I_PastMonth_(include),...
    ...
    tb.cp1(include),tb.cp2(include),tb.cp3(include),...
    tb.cp4(include),tb.cp5(include),...
    ...
    tb.alpha_t(include_gain), tb.beta_t(include_gain),...
    tb.alpha_t(include_loss), tb.beta_t(include_loss),...
    tb.r(include_gain), tb.a_r50(include_gain),...
    tb.r(include_loss), tb.a_r50(include_loss),...
    ...
    'VariableNames',...
    {'id', 'age',...
    'CAPSpm','CAPSlt', 'PCLM',...       % PTSD
    'CTQ','CES','DRRI',...                      % Trauma 
    'BDI','STAI1','STAI2','BAI',...             % Axiety and depression
    'ASIalcohol','ASIdrug',...             
    'DERS','DES','FSS','RSES','RLOCS',...
    ...
    'Reex','Avoid','Numb','Dysph','Anx',...
    ...
    'CP1', 'CP2', 'CP3', 'CP4', 'CP5',...
    ...
    'RGmb','AGmb',...
    'RLmb', 'ALmb',...
    'RGmf','AGmf',...
    'RLmf', 'ALmf',...
    });

%% Calculate components PCA 13 measures
include_gain = tb.isExcluded_behavior == 0 & tb.isGain == 1;
include_loss = tb.isExcluded_behavior == 0 & tb.isGain == 0;

include = include_gain;

% load PCA loadings
loadingsfilename = fullfile(root,'pca loadings 13.xlsx');

loadings = readtable(loadingsfilename);


% exclude the one with an extreme ASI alcohol score
tb.asi_alcohol(tb.asi_alcohol>1) = NaN;

% calculate PCA component
tb.cp1 = nanzscore([tb.caps_totalscorem,...
    tb.pclm_total,...
    tb.ctq_total,tb.ces_total,tb.drri2_combat_exposure_total,...
    tb.bdiii_total,tb.stai_x1_total, tb.stai_x2_total,...
    tb.bai_total,...
    tb.asi_alcohol_dayspm,tb.asi_drug_dayspm,...
    tb.ders_total,tb.des_total_mean])...
    * table2array(loadings(:,2));

tb.cp2 = nanzscore([tb.caps_totalscorem,...
    tb.pclm_total,...
    tb.ctq_total,tb.ces_total,tb.drri2_combat_exposure_total,...
    tb.bdiii_total,tb.stai_x1_total, tb.stai_x2_total,...
    tb.bai_total,...
    tb.asi_alcohol_dayspm,tb.asi_drug_dayspm,...
    tb.ders_total,tb.des_total_mean])...
    * table2array(loadings(:,3));

tb.cp3 = nanzscore([tb.caps_totalscorem,...
    tb.pclm_total,...
    tb.ctq_total,tb.ces_total,tb.drri2_combat_exposure_total,...
    tb.bdiii_total,tb.stai_x1_total, tb.stai_x2_total,...
    tb.bai_total,...
    tb.asi_alcohol_dayspm,tb.asi_drug_dayspm,...
    tb.ders_total,tb.des_total_mean])...
    * table2array(loadings(:,4));

tb.cp4 = nanzscore([tb.caps_totalscorem,...
    tb.pclm_total,...
    tb.ctq_total,tb.ces_total,tb.drri2_combat_exposure_total,...
    tb.bdiii_total,tb.stai_x1_total, tb.stai_x2_total,...
    tb.bai_total,...
    tb.asi_alcohol_dayspm,tb.asi_drug_dayspm,...
    tb.ders_total,tb.des_total_mean])...
    * table2array(loadings(:,5));

tb.cp5 = nanzscore([tb.caps_totalscorem,...
    tb.pclm_total,...
    tb.ctq_total,tb.ces_total,tb.drri2_combat_exposure_total,...
    tb.bdiii_total,tb.stai_x1_total, tb.stai_x2_total,...
    tb.bai_total,...
    tb.asi_alcohol_dayspm,tb.asi_drug_dayspm,...
    tb.ders_total,tb.des_total_mean])...
    * table2array(loadings(:,6));

%% create table for multilinear model PCA 13
tb2ml = table(tb.id(include), tb.age(include),...
    tb.caps_totalscorem(include),tb.caps_totalscorel(include),...
    tb.pclm_total(include),...
    tb.ctq_total(include),tb.ces_total(include),tb.drri2_combat_exposure_total(include),...
    tb.bdiii_total(include),tb.stai_x1_total(include), tb.stai_x2_total(include),...
    tb.bai_total(include),...
    tb.asi_alcohol(include),tb.asi_drug(include),...
    tb.ders_total(include),tb.des_total_mean(include),tb.fssii_total(include),...
    tb.rses_total(include),tb.rlocscale_total(include),...
    ...
    tb.R_F_I_PastMonth_(include),...
    tb.A_F_I_PastMonth_(include), tb.N_F_I_PastMonth_(include),...
    tb.DA_F_I_PastMonth_(include), tb.AA_F_I_PastMonth_(include),...
    ...
    tb.cp1(include),tb.cp2(include),tb.cp3(include),...
    tb.cp4(include),tb.cp5(include),...
    ...
    tb.alpha_t(include_gain), tb.beta_t(include_gain),...
    tb.alpha_t(include_loss), tb.beta_t(include_loss),...
    tb.r(include_gain), tb.a_r50(include_gain),...
    tb.r(include_loss), tb.a_r50(include_loss),...
    ...
    'VariableNames',...
    {'id', 'age',...
    'CAPSpm','CAPSlt', 'PCLM',...       % PTSD
    'CTQ','CES','DRRI',...                      % Trauma 
    'BDI','STAI1','STAI2','BAI',...             % Axiety and depression
    'ASIalcohol','ASIdrug',...             
    'DERS','DES','FSS','RSES','RLOCS',...
    ...
    'Reex','Avoid','Numb','Dysph','Anx',...
    ...
    'CP1', 'CP2', 'CP3', 'CP4', 'CP5',...
    ...
    'RGmb','AGmb',...
    'RLmb', 'ALmb',...
    'RGmf','AGmf',...
    'RLmf', 'ALmf',...
    });

%% correlation bwtween components and behavior
tb2plot2 = table(tb2ml.RGmb, tb2ml.AGmb, tb2ml.RLmb, tb2ml.ALmb,...
    'VariableNames',{'RGmb','AGmb','RLmb', 'ALmb'});
 
tb2plot1 = table(tb2ml.CP1, tb2ml.CP2, tb2ml.CP3,tb2ml.CP4,tb2ml.CP5,...
    'VariableNames',{'CP1','CP2','CP3','CP4','CP5'});

plotcorrmat2(tb2plot1, tb2plot2,1)

%%
tb2image = tb(tb.isExcluded_imaging == 0 & tb.isGain == 0,:);

%% including
cluster = {'Re-experiencing','Avoidance','Emotional Numbing','Dysphoric Arousal','Anxious Arousal','Total'};
param = {'alpha','beta'};
domain = {'gain','loss'};

% which group to look at
include = strcmp(tb.group, 'P') & tb.isExcluded_behavior == 0;
% Include all subjects
include = (strcmp(tb.group, 'C') | strcmp(tb.group, 'P') | strcmp(tb.group, 'R')) & tb.isExcluded_behavior == 0;
% Include PTSD and control subjects
include = (strcmp(tb.group, 'C') | strcmp(tb.group, 'P')) & tb.isExcluded_behavior == 0;

include = tb.isExcluded_behavior == 0;

include_gain = (strcmp(tb.group, 'C') | strcmp(tb.group, 'P')) &...
    tb.isExcluded_behavior == 0 & tb.isGain == 1;

include_loss = (strcmp(tb.group, 'C') | strcmp(tb.group, 'P')) &...
    tb.isExcluded_behavior == 0 & tb.isGain == 0;

include_gain = (tb.isExcluded_behavior == 0 & tb.isGain == 1);

include_loss = (tb.isExcluded_behavior == 0 & tb.isGain == 0);

% number of controls
ncontrol = sum(tb.isGain == 1 & strcmp(tb.group, 'C') & tb.isExcluded_behavior == 0)
% number of PTSDs
nptsd = sum(tb.isGain == 1 & strcmp(tb.group, 'P') & tb.isExcluded_behavior == 0)
% number of remitted PTSDs
nrptsd = sum(tb.isGain == 1 & strcmp(tb.group, 'R') & tb.isExcluded_behavior == 0)


% caculate model free scores
% tb.r = nanmean([tb.r25, tb.r50, tb.r75],2);
% tb.a_r50 = nanmean([tb.a24_r50, tb.a50_r50, tb.a74_r50],2);
% save 'all data.mat' 'tb'

%% correlation bwteen behavior scores
behav2plot = table(tb.alpha_t(include_gain),tb.beta_t(include_gain),...
    tb.alpha_t(include_loss), tb.beta_t(include_loss),...
    tb.r(include_gain), tb.a_r50(include_gain),...
    tb.r(include_loss), tb.a_r50(include_loss),...
    'VariableNames',{'RGmb','AGmb','RLmb', 'ALmb',...
                     'RGmf','AGmf','RLmf', 'ALmf'});

plotcorrmat1(behav2plot,1)

%% create a table for imaging covariates

include_gain = (tb.isExcluded_imaging == 0 & tb.isGain == 1);

include_loss = (tb.isExcluded_imaging == 0 & tb.isGain == 0);


tbcov = table(tb.id(include_gain), tb.isExcluded_behavior(include_gain), tb.isExcluded_imaging(include_gain),...
    tb.R_F_I_PastMonth_(include_gain), tb.A_F_I_PastMonth_(include_gain), tb.N_F_I_PastMonth_(include_gain),...
    tb.DA_F_I_PastMonth_(include_gain), tb.AA_F_I_PastMonth_(include_gain),...
    tb.caps_totalscorem(include_gain),...
    tb.alpha_t(include_gain),tb.beta_t(include_gain),...
    tb.alpha_t(include_loss), tb.beta_t(include_loss),...
    tb.r(include_gain), tb.a_r50(include_gain),...
    tb.r(include_loss), tb.a_r50(include_loss),...
    'VariableNames',{'id','ExcBehavior','ExcImaging',...
    'Reex','Avoid','Numb','Dysph','Anx','Total',...
    'RGmb','AGmb','RLmb', 'ALmb',...
    'RGmf','AGmf','RLmf', 'ALmf'});

% save tb_cov.mat tbcov                 
writetable(tbcov,fullfile(root,'covariate_imaging_05162018.xlsx'));
%% Multilinear regression, model based
% risk gain
multiTb = tb(include_gain, :);
multiLm = fitlm(multiTb, 'alpha_t~R_fi_pm+A_fi_pm+N_fi_pm+DA_fi_pm+AA_fi_pm')
multiLm = fitlm(multiTb, 'alpha_t~caps_total_lt')


% ambig gain
multiTb = tb(include_gain, :);
multiLm = fitlm(multiTb, 'beta_t~R_fi_pm+A_fi_pm+N_fi_pm+DA_fi_pm+AA_fi_pm')
multiLm = fitlm(multiTb, 'beta_t~caps_total_pm')

% risk loss
multiTb = tb(include_loss, :);
multiLm = fitlm(multiTb, 'alpha_t~R_fi_pm+A_fi_pm+N_fi_pm+DA_fi_pm+AA_fi_pm')
multiLm = fitlm(multiTb, 'alpha_t~caps_total_pm')

% ambig loss
multiTb = tb(include_loss, :);
multiLm = fitlm(multiTb, 'beta_t~R_fi_pm+A_fi_pm+N_fi_pm+DA_fi_pm+AA_fi_pm')
multiLm = fitlm(multiTb, 'beta_t~caps_total_lt')


%% all plots
for i = 1:length(cluster)
    cluster2plot = cluster{i};
    for j = 1:length(param)
        param2plot = param{j};
        for k = 1:length(domain)
            domain2plot = domain(k);
            
            if strcmp(domain2plot,'gain')
                domainIdx = (tb.isGain == 1);
            else
                domainIdx = (tb.isGain == 0);
            end
            
            if strcmp(cluster2plot,'Total')
                x = tb.caps_total_pm(tb.isExcluded_behavior == 0 & domainIdx & include);
            elseif strcmp(cluster2plot,'Re-experiencing')
                x = tb.R_fi_pm(tb.isExcluded_behavior == 0 & domainIdx & include);
            elseif strcmp(cluster2plot,'Avoidance')
                x = tb.A_fi_pm(tb.isExcluded_behavior == 0 & domainIdx & include);
            elseif strcmp(cluster2plot,'Emotional Numbing')
                x = tb.N_fi_pm(tb.isExcluded_behavior == 0 & domainIdx & include);
            elseif strcmp(cluster2plot,'Dysphoric Arousal')
                x = tb.DA_fi_pm(tb.isExcluded_behavior == 0 & domainIdx & include);
            elseif strcmp(cluster2plot,'Anxious Arousal')
                x = tb.AA_fi_pm(tb.isExcluded_behavior == 0 & domainIdx & include);
            end

            if strcmp(param2plot, 'alpha')
                y = tb.alpha_t(tb.isExcluded_behavior == 0 & domainIdx & include);
            elseif strcmp(param2plot, 'beta')
                y = tb.beta_t(tb.isExcluded_behavior == 0 & domainIdx & include);
            end
            
            plotcorr(x,y,cluster2plot,[param2plot '-' domain2plot]);


            %     x = tb.N_fi_pm(tb.isExcluded_behavior == 0 & tb.isGain == 0);
            %     x = tb.caps_total_pm(tb.isExcluded_behavior == 0 & tb.isGain == 0);
            %     y = tb.beta_t(tb.isExcluded_behavior == 0 & tb.isGain == 0);

                % save the plot
        end
    end
end

%% specify plot
cluster2plot = 'Total';
param2plot = 'beta';
domain2plot = 'loss';

if strcmp(domain2plot,'gain')
    domainIdx = (tb.isGain == 1);
else
    domainIdx = (tb.isGain == 0);
end

if strcmp(cluster2plot,'Total')
    x = tb.caps_total_pm(tb.isExcluded_behavior == 0 & domainIdx);
elseif strcmp(cluster2plot,'Re-experiencing')
    x = tb.R_fi_pm(tb.isExcluded_behavior == 0 & domainIdx);
elseif strcmp(cluster2plot,'Avoidance')
    x = tb.A_fi_pm(tb.isExcluded_behavior == 0 & domainIdx);
elseif strcmp(cluster2plot,'Emotional Numbing')
    x = tb.N_fi_pm(tb.isExcluded_behavior == 0 & domainIdx);
elseif strcmp(cluster2plot,'Dysphoric Arousal')
    x = tb.DA_fi_pm(tb.isExcluded_behavior == 0 & domainIdx);
elseif strcmp(cluster2plot,'Anxious Arousal')
    x = tb.AA_fi_pm(tb.isExcluded_behavior == 0 & domainIdx);
end

if strcmp(param2plot, 'alpha')
    y = tb.alpha_t(tb.isExcluded_behavior == 0 & domainIdx);
elseif strcmp(param2plot, 'beta')
    y = tb.beta_t(tb.isExcluded_behavior == 0 & domainIdx);
end


plotcorr(x,y,cluster2plot,[param2plot '-' domain2plot]);

%% correlation matrix

x = tb.caps_total_pm(include_gain);
y = tb.beta_t(include_loss);
plotcorr(x,y,'caps','beta loss')

% PTSD measurements
tb2plot_clinical = table(tb.caps_totalscorem(include_gain),tb.pcl5_total(include_gain),...
    tb.pclm_total(include_gain), 'VariableNames',{'CAPStotal', 'PCL5','PCLM'});



% caps five factors
tb2plot_clinical = table(tb.caps_totalscorem(include_gain),tb.R_F_I_PastMonth_(include_gain),...
    tb.A_F_I_PastMonth_(include_gain), tb.N_F_I_PastMonth_(include_gain),...
    tb.DA_F_I_PastMonth_(include_gain), tb.AA_F_I_PastMonth_(include_gain),...
    'VariableNames',{'Total','Reex','Avoid','Numb','Dysph','Anx'});

% anxiety and depression measurement
tb2plot_clinical = table(...
    tb.bdiii_total(include_gain),...
    tb.stai_x1_total(include_gain), tb.stai_x2_total(include_gain), tb.bai_total(include_gain),...
    'VariableNames',{'BDI','STAI1','STAI2',...
    'BAI'});



% all clinical measurement
tb2plot_clinical = table(...
    tb.bdiii_total(include_gain), tb.madrs_total(include_gain), tb.hama_total(include_gain),...
    tb.stai_x1_total(include_gain), tb.stai_x2_total(include_gain), tb.bai_total(include_gain),...
    tb.rses_total(include_gain),tb.ftnd_total(include_gain),tb.ders_total(include_gain),...
    tb.des_total_mean(include_gain),tb.fssii_total(include_gain),tb.rlocscale_total(include_gain),...
    tb.bis11_total(include_gain),...
    'VariableNames',{'BDI','MADRS','HARS','STAI1','STAI2',...
    'BAI','RSES','FTND','DERS','DES','FSS','RLOCS','BIS11'});

% all combat and trauma measurement
tb2plot_clinical = table(tb.ctq_total(include_gain),tb.ces_total(include_gain),...
    tb.drri2_combat_exposure_total(include_gain),...
    'VariableNames',{'CTQ', 'CES','DRRI'});

% age, intelligence
tb2plot_clinical = table(tb.age(include_gain),tb.kbit(include_gain),...
    'VariableNames',{'Age', 'KBIT'});


% model based behavior
tb2plot_behav = table(tb.alpha_t(include_gain), tb.beta_t(include_gain),...
    tb.alpha_t(include_loss), tb.beta_t(include_loss),...
    'VariableNames',{'alphaGain', 'betaGain','alphaLoss','betaLoss'});

% model free behavior
tb2plot_behav = table(tb.r(include_gain), tb.a_r50(include_gain),...
    tb.r(include_loss), tb.a_r50(include_loss),...
    'VariableNames',{'riskGain', 'ambigGain','riskLoss','ambigLoss'});

% plot correlation scatter plot matrix
plotcorrmat2(tb2plot_clinical, tb2plot_behav,1)

%% partial least square regression (an supervised alternative to principal component regression)

% set up table, risk gain model estimate ~ PC(CAPS, BDI, BAI, CES, Addiction......)
tb2pls = table(tb.alpha_t(include_gain),tb.caps_totalscorem(include_gain),...
    tb.bdiii_total(include_gain), tb.bai_total(include_gain),...
    'VariableNames',{'RiskGain','CAPStotal','BDI', 'BAI'});

tb2pls = table(tb.alpha_t(include_gain),...
    tb.bdiii_total(include_gain), tb.bai_total(include_gain),...
    'VariableNames',{'RiskGain','BDI', 'BAI'});

tb2pls = table(tb.alpha_t(include_gain),tb.caps_totalscorem(include_gain),...
    tb.bdiii_total(include_gain),...
    tb.stai_x1_total(include_gain), tb.stai_x2_total(include_gain),...
    tb.bai_total(include_gain),...
    'VariableNames',{'RiskGain','CAPStotal', 'BDI', 'STAI1','STAI2','BAI'});


% exclude rows with NaNs
tb2pls = tb2pls(~any(ismissing(tb2pls),2),:);

% standardizing each predictor
x = nanzscore(table2array(tb2pls(:,2:size(tb2pls,2))));
% standardizing the dependent variable
y = nanzscore(table2array(tb2pls(:,1)));

% PLS regression with the number of components equal to the number of
% predictors
[Xloadings,Yloadings,Xscores,Yscores,betaPLS,PLSPctVar,MSE] = plsregress(...
	x,y,size(tb2pls,2)-1);

% plot variance explained by each component
figure
plot(1:size(tb2pls,2)-1,cumsum(100*PLSPctVar(2,:)),'-bo');
xlabel('Number of PLS components');
ylabel('Percent Variance Explained in Y');

% decide to use only 2 components
cp2use = 2;
[Xloadings,Yloadings,Xscores,Yscores,betaPLS,PLSPctVar,MSE] = plsregress(...
	x,y,cp2use);

% plot variance explained by each component
figure
plot(1:cp2use,cumsum(100*PLSPctVar(2,:)),'-bo');
xlabel('Number of PLS components');
ylabel('Percent Variance Explained in Y');

% plot the correlation between each component and dependent variable
figure
scatter(Xscores(:,1), y)
hold on
scatter(Xscores(:,2),y)



